"""Run one or more offline eviction simulations and emit a single safety gate."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from astrakv.runtime.offline_safety import OfflineSafetyGate, write_gate  # noqa: E402


REQUIRED = ("workload_id", "workload_manifest", "trace", "profile_db", "gpu_capacity_bytes", "cpu_capacity_bytes", "ssd_capacity_bytes", "default_object_bytes", "profile_source")


def main() -> int:
    args = parse_args()
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    entries = load_entries(args)
    manifests: list[dict[str, Any]] = []
    errors: list[str] = []
    for entry in entries:
        try:
            validate_entry(entry)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        item_output = output / "workloads" / str(entry["workload_id"])
        command = simulator_command(entry, args.run_id, item_output)
        result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
        (item_output / "pipeline_command.json").parent.mkdir(parents=True, exist_ok=True)
        (item_output / "pipeline_command.json").write_text(json.dumps({"command": command, "returncode": result.returncode, "stdout": result.stdout, "stderr": result.stderr}, indent=2, ensure_ascii=False), encoding="utf-8")
        manifest_path = item_output / "offline_eviction_manifest.json"
        if result.returncode == 0 and manifest_path.exists():
            manifests.append(json.loads(manifest_path.read_text(encoding="utf-8")))
        else:
            errors.append(f"{entry['workload_id']}: simulator failed with exit {result.returncode}")
    gate = OfflineSafetyGate.evaluate(manifests)
    if errors:
        gate = OfflineSafetyGate.evaluate([])
        payload = gate.result.to_record()
        payload["reasons"] = errors + payload["reasons"]
        payload["status"] = "rejected"
        (output / "offline_safety_gate.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    else:
        write_gate(output / "offline_safety_gate.json", gate)
    status = {
        "schema": "astrakv-offline-pipeline-status-v1",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "run_id": args.run_id,
        "status": "accepted" if not errors and gate.result.allowed else "rejected",
        "workload_count": len(entries),
        "successful_manifest_count": len(manifests),
        "errors": errors,
        "gate": str(output / "offline_safety_gate.json"),
        "manifests": [str(output / "workloads" / str(item.get("workload_id")) / "offline_eviction_manifest.json") for item in entries],
    }
    (output / "offline_pipeline_status.json").write_text(json.dumps(status, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Offline eviction pipeline {status['status']}: {output}")
    return 0 if status["status"] == "accepted" else 2


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workload-set", required=True, help="JSON with schema and workloads array")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--output-dir", default="results/offline_eviction_pipeline")
    parser.add_argument("--append-current", default="", help="Optional JSON workload entry generated by an entrypoint")
    return parser.parse_args()


def load_entries(args: argparse.Namespace) -> list[dict[str, Any]]:
    payload = json.loads(Path(args.workload_set).read_text(encoding="utf-8"))
    if payload.get("schema") != "astrakv-offline-workload-set-v1" or not isinstance(payload.get("workloads"), list):
        raise SystemExit("offline workload set must use schema astrakv-offline-workload-set-v1 and a workloads array")
    entries = [dict(item) for item in payload["workloads"] if isinstance(item, dict)]
    if args.append_current:
        current = json.loads(Path(args.append_current).read_text(encoding="utf-8"))
        if isinstance(current, dict):
            entries.append(current)
    return entries


def validate_entry(entry: dict[str, Any]) -> None:
    missing = [name for name in REQUIRED if entry.get(name) in (None, "")]
    if missing:
        raise ValueError(f"offline workload entry missing: {', '.join(missing)}")
    if entry["profile_source"] != "separate_profiling_run":
        raise ValueError(f"{entry['workload_id']}: profile_source must be separate_profiling_run for a runtime-eligible pipeline")
    for name in ("workload_manifest", "trace", "profile_db"):
        if not Path(str(entry[name])).exists():
            raise ValueError(f"{entry['workload_id']}: missing {name}: {entry[name]}")


def simulator_command(entry: dict[str, Any], run_id: str, output: Path) -> list[str]:
    command = [sys.executable, "scripts/policy/run_offline_eviction_simulator.py", "--workload-manifest", str(entry["workload_manifest"]), "--trace", str(entry["trace"]), "--profile-db", str(entry["profile_db"]), "--workload-id", str(entry["workload_id"]), "--run-id", run_id, "--gpu-capacity-bytes", str(entry["gpu_capacity_bytes"]), "--cpu-capacity-bytes", str(entry["cpu_capacity_bytes"]), "--ssd-capacity-bytes", str(entry["ssd_capacity_bytes"]), "--default-object-bytes", str(entry["default_object_bytes"]), "--profile-source", str(entry["profile_source"]), "--output-dir", str(output)]
    for option, name in (("--request-results", "request_results"), ("--scheduler-decisions", "scheduler_decisions"), ("--cpu-to-gpu-ms", "cpu_to_gpu_ms"), ("--ssd-to-gpu-ms", "ssd_to_gpu_ms"), ("--recompute-ms", "recompute_ms")):
        if entry.get(name) not in (None, ""):
            command.extend((option, str(entry[name])))
    return command


if __name__ == "__main__":
    raise SystemExit(main())
